# Generated by Django 3.2 on 2021-06-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210524_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideatree',
            name='passcode',
            field=models.CharField(default=True, max_length=6),
        ),
    ]
