# Generated by Django 3.2 on 2021-05-24 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('path', models.IntegerField()),
                ('color', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IdeaTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('overview', models.CharField(max_length=300)),
                ('complete_flag', models.IntegerField()),
                ('idea_theme', models.CharField(max_length=300)),
                ('lastidea_id', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.publisher')),
            ],
        ),
        migrations.DeleteModel(
            name='Elment',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.RemoveField(
            model_name='store',
            name='books',
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.AddField(
            model_name='element',
            name='ideaTree_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ideatree'),
        ),
    ]
