# Generated by Django 2.1.7 on 2021-07-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='noname', max_length=150, unique=True, verbose_name='username'),
        ),
    ]
