# Generated by Django 3.2 on 2021-05-24 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210524_0550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='ideaTree_id',
            new_name='ideatree',
        ),
        migrations.RenameField(
            model_name='ideatree',
            old_name='user_id',
            new_name='user',
        ),
    ]
