# Generated by Django 2.1.7 on 2021-07-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='noname', max_length=150, verbose_name='username'),
        ),
    ]
