# Generated by Django 3.2 on 2021-06-04 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_ideatree_passcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideatree',
            name='passcode',
        ),
    ]
