# Generated by Django 3.2 on 2021-06-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_ideatree_passcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideatree',
            name='passcode',
            field=models.CharField(default=True, max_length=6),
        ),
    ]
